apiVersion: apps/v1
kind: Deployment
metadata:
name: backend-api-books
spec:
replicas: 4
selector:
  matchLabels:
    role: bookapi
template:
  metadata:
    labels:
      role: bookapi
  spec:
    containers:
      - name: backend-api-books
        image: registryRosaura.azurecr.io/backend-api-books:v1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
    imagePullSecrets:
      - name: palabra-super-secreta

---
apiVersion: v1
kind: Service
metadata:
  name: load-balancer
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 8000
  selector:
    role: bookapi
