apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api-iris
spec:
  replicas: 4
  selector:
    matchLabels:
      role: rediris
  template:
    metadata:
      labels:
        role: rediris
    spec:
      containers:
        - name: backend-api-iris
          image: registryRosaura.azurecr.io/backend_books:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
      imagePullSecrets:
        - name: backend-api-iris

---
apiVersion: v1
kind: Service
metadata:
  name: load-balancer
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 8000
  selector:
    role: rediris
